apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ixse
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ixse
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ixse
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ixse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ixse
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cxgg-tenant/rhtap-demo-app/hacbs-test-project-ixse@sha256:406754a787349d9b819b0348fe44bfbb056125f325331bfce89a1f6c0fbc5d09
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
